import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Domain Knowledge',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-knowledge',
        },
      ],
    },
    {
      type: 'category',
      label: 'Project Docs',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'project-docs',
        },
      ],
    },
  ],
};

export default sidebars;
